### ISSUE TITLE
No binary from 2020 in Releases

### ISSUE THREAD

**Issue by rodneyrod** [banjun/imastodon#29]
Hi,

Just noticed that the latest binary in Releases is from last year, would it be possible to update this to a more recent version?

**Comment by banjun** [comment]
Yes, I have to have some time to do that...
Do you use a binary release version?

**Comment by rodneyrod** [comment]
Yes, been having issues with dependencies when trying to build with Xcode

**Comment by banjun** [comment]
Now you can try this https://github.com/banjun/imastodon/releases/tag/mac%2F1.0.0-alpha.5

**Comment by rodneyrod** [comment]
Thanks confirmed new app is working, really appreciate the work 😄
